language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t abhishlohithan/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true abhishlohithan/docker-react npm run test  

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-134224775140"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY