version: '3'
services: 
  web: 
    build: 
      context: .
      dockerfile: Dockerfile.devohttps://www.youtube.com/watch?v=SleynAZ1pfQpopkay
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
    environment: 
      - CHOKIDAR_USEPOLLING